version: "3"
services:
  web:
    image: nginx
    ports:
      - "8080:80"

...
# Map
# ├── version: "3"
# └── services (Map)
#   └── web (Map)
#     ├── image: nginx
#     └── ports (List)
#     └── "8080:80"

